import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'startContainer.dart';

class SubmitPage extends StatefulWidget {
  const SubmitPage({Key key}) : super(key: key);

  @override
  _SubmitPageState createState() => _SubmitPageState();
}

class _SubmitPageState extends State<SubmitPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // body: SingleChildScrollView(
      //   child: Column(
      //     children: [
      //       ElevatedButton(
      //         style: ButtonStyle(
      //           backgroundColor: MaterialStateProperty.all(Color(0xff0D9F0E)),
      //           shape: MaterialStateProperty.all(
      //             RoundedRectangleBorder(
      //               borderRadius: BorderRadius.circular(15),
      //             ),
      //           ),
      //         ),
      //         onPressed: () {},
      //         child: Padding(
      //           padding: const EdgeInsets.only(left: 30, right: 30),
      //           child: Text(
      //             "Sumbit Page",
      //             style: TextStyle(fontSize: 25, fontWeight: FontWeight.bold),
      //           ),
      //         ),
      //       ),
      //       Padding(
      //       padding: EdgeInsets.only(top: 120,right: 20,left: 20),
      //       child: Column(
      //         crossAxisAlignment: CrossAxisAlignment.start,
      //         children: [
      //           Padding(
      //             padding: const EdgeInsets.all(6.0),
      //             child: Text("Thank You",style: TextStyle(fontSize: 18),),
      //           ),
      //           TextField(
      //             decoration: InputDecoration(
      //                 border: OutlineInputBorder(),
      //                 labelText: "Thank you for your time and please click\non the green button to complete the survey"),
      //           ),
      //           SizedBox(height: 20,),
      //           Padding(
      //             padding: const EdgeInsets.all(6.0),
      //             child: Text("Date & Time of Survey",style: TextStyle(fontSize: 18),),
      //           ),
      //           TextField(
      //             decoration: InputDecoration(
      //                 border: OutlineInputBorder(),
      //                 labelText: "Auto generated by the system"),
      //           ),

      //         ],
      //       ),
      //     ),
      //     StartContainer()
      //     ],
      //   ),
      // ),

      body: SafeArea(
        child: Stack(
          children: [
            Container(
              height: double.infinity,
              width: double.infinity,
              color: Colors.white,
            ),
            SingleChildScrollView(
              child: Column(
                children: [
                  Padding(
                    padding: const EdgeInsets.only(top:20),
                    child: ElevatedButton(
                      style: ButtonStyle(
                        backgroundColor:
                            MaterialStateProperty.all(Color(0xff0D9F0E)),
                        shape: MaterialStateProperty.all(
                          RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(15),
                          ),
                        ),
                      ),
                      onPressed: () {},
                      child: Padding(
                        padding: const EdgeInsets.only(left: 30, right: 30),
                        child: Text(
                          "Sumbit Page",
                          style:
                              TextStyle(fontSize: 25, fontWeight: FontWeight.bold),
                        ),
                      ),
                    ),
                  ),
                  Padding(
                    padding: EdgeInsets.only(top: 20, right: 20, left: 20),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Padding(
                          padding: const EdgeInsets.all(6.0),
                          child: Text(
                            "Thank You",
                            style: TextStyle(fontSize: 18),
                          ),
                        ),
                        TextField(
                          decoration: InputDecoration(
                              border: OutlineInputBorder(),
                              labelText:
                                  "Thank you for your time and please click\non the green button to complete the survey"),
                        ),
                        SizedBox(
                          height: 20,
                        ),
                        Padding(
                          padding: const EdgeInsets.all(6.0),
                          child: Text(
                            "Date & Time of Survey",
                            style: TextStyle(fontSize: 18),
                          ),
                        ),
                        TextField(
                          decoration: InputDecoration(
                              border: OutlineInputBorder(),
                              labelText: "Auto generated by the system"),
                        ),
                      ],
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(top: 20),
                    child: GestureDetector(
                      onTap: (){},
                      child: Container(
                        child: Center(
                          child: Text(
                            "Start",
                            style: TextStyle(
                                color: Color(0xffDDE0CF),
                                fontSize: 35,
                                fontWeight: FontWeight.bold),
                          ),
                        ),
                        decoration: BoxDecoration(
                            color: Color(0xff0D9F0E),
                            borderRadius: BorderRadius.circular(100)),
                        height: 180,
                        width: 180,
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(right: 150,top: 10),
                    child: Container(
                      height: 70,
                      width: 70,
                      decoration: BoxDecoration(
                          color: Color(0xff0D9F0E),
                          borderRadius: BorderRadius.circular(100)),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(right:230,top: 10),
                    child: Container(
                      height: 35,
                      width: 35,
                      decoration: BoxDecoration(
                          color: Color(0xff0D9F0E),
                          borderRadius: BorderRadius.circular(35)),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(top: 30),
                    child: Text(
                        "Powered by CropIntellix Pvt Ltd\n   Visit www.cropintellix.com",
                        style: TextStyle(color: Colors.grey)),
                  ),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }
}
